FROM rust:1.90-bookworm AS builder

RUN apt-get update && apt-get install -y \
    zlib1g zlib1g-dev \
    cmake \
    libssl-dev \
    libsasl2-dev \
    libzstd-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Cargo.toml ./
COPY src ./src

RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    zlib1g \
    libssl3 \
    libsasl2-2 \
    libzstd1 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m appuser
USER appuser

COPY --from=builder /app/target/release/wallet-bff /wallet-bff

EXPOSE 8088

CMD ["/wallet-bff"]
